-- Plotto Phase 1 — Row Level Security + auth.users sync
-- Complements 0000_purple_dark_phoenix.sql (generated by drizzle-kit).

-- ─── trigger: auto-provision public.users on signup ─────────────────────────
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email)
  values (new.id, coalesce(new.email, ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ─── trigger: updated_at ────────────────────────────────────────────────────
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists users_touch_updated_at on public.users;
create trigger users_touch_updated_at
before update on public.users
for each row execute function public.touch_updated_at();

drop trigger if exists events_touch_updated_at on public.events;
create trigger events_touch_updated_at
before update on public.events
for each row execute function public.touch_updated_at();

-- ─── Row Level Security ─────────────────────────────────────────────────────
alter table public.users      enable row level security;
alter table public.captures   enable row level security;
alter table public.events     enable row level security;
alter table public.reminders  enable row level security;

-- users: only the owner can read/write their own profile row.
drop policy if exists users_self_select on public.users;
create policy users_self_select on public.users
  for select using (auth.uid() = id);

drop policy if exists users_self_update on public.users;
create policy users_self_update on public.users
  for update using (auth.uid() = id) with check (auth.uid() = id);

-- captures: owner full access.
drop policy if exists captures_owner_all on public.captures;
create policy captures_owner_all on public.captures
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- events: owner full access.
drop policy if exists events_owner_all on public.events;
create policy events_owner_all on public.events
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- reminders: follow parent event ownership.
drop policy if exists reminders_owner_all on public.reminders;
create policy reminders_owner_all on public.reminders
  for all using (
    exists (
      select 1 from public.events e
      where e.id = reminders.event_id and e.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.events e
      where e.id = reminders.event_id and e.user_id = auth.uid()
    )
  );

-- ─── helpful indexes ────────────────────────────────────────────────────────
create index if not exists events_user_starts_idx
  on public.events (user_id, starts_at);
create index if not exists events_user_status_idx
  on public.events (user_id, status);
create index if not exists captures_user_created_idx
  on public.captures (user_id, created_at desc);
create index if not exists reminders_fires_idx
  on public.reminders (fires_at) where fired = false;
